-- KAPTURISE AI AGENTS — Supabase Database Schema
CREATE TABLE agents (id TEXT PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL, title TEXT, avatar TEXT DEFAULT '🤖', pic TEXT, ethnicity TEXT, background TEXT, status TEXT DEFAULT 'active', config JSONB DEFAULT '{}', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE leads (id SERIAL PRIMARY KEY, name TEXT NOT NULL, website TEXT, industry TEXT, stage TEXT DEFAULT 'Research', contact_name TEXT, contact_title TEXT, email TEXT, phone TEXT, instagram TEXT, linkedin TEXT, value INTEGER DEFAULT 0, notes TEXT, requirements TEXT, source TEXT, source_type TEXT, assigned_to TEXT REFERENCES agents(id), service_type TEXT, logs JSONB DEFAULT '[]', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE investors (id SERIAL PRIMARY KEY, fund TEXT NOT NULL, fund_size TEXT, thesis TEXT, stage_focus TEXT, partner_name TEXT, partner_title TEXT, email TEXT, phone TEXT, linkedin TEXT, check_min INTEGER DEFAULT 0, check_max INTEGER DEFAULT 0, portfolio TEXT, stage TEXT DEFAULT 'Research', pitch_deck TEXT DEFAULT 'Not sent', dd_status TEXT DEFAULT '—', term_sheet TEXT DEFAULT '—', meeting_notes TEXT, next_follow_up DATE, assigned_to TEXT REFERENCES agents(id), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE pricing (id TEXT PRIMARY KEY, name TEXT NOT NULL, icon TEXT DEFAULT '📦', base_price INTEGER DEFAULT 0, unit TEXT DEFAULT 'AED', base_hours INTEGER DEFAULT 0, note TEXT, includes JSONB DEFAULT '[]', addons JSONB DEFAULT '[]', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE campaigns (id SERIAL PRIMARY KEY, name TEXT NOT NULL, url TEXT, special_offer TEXT, custom_pricing TEXT, assigned_agents JSONB DEFAULT '[]', service_type TEXT, dm_script TEXT, email_script TEXT, call_script TEXT, content_brief TEXT, prospects TEXT, status TEXT DEFAULT 'active', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE scripts (id SERIAL PRIMARY KEY, category TEXT NOT NULL, name TEXT NOT NULL, subject TEXT, body TEXT, channel TEXT, assigned_agents JSONB DEFAULT '[]', assigned_campaigns JSONB DEFAULT '[]', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE social_accounts (id TEXT PRIMARY KEY, name TEXT NOT NULL, platform TEXT, account_type TEXT, access_token TEXT, status TEXT DEFAULT 'pending', followers INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE company_info (id INTEGER PRIMARY KEY DEFAULT 1, name TEXT DEFAULT 'Kapturise', tagline TEXT DEFAULT 'Make it your moment.', owner_name TEXT, owner_title TEXT DEFAULT 'Founder & CEO', owner_email TEXT, owner_phone TEXT, email TEXT, phone TEXT, website TEXT DEFAULT 'www.kapturise.com', address TEXT DEFAULT 'Dubai, UAE', license TEXT, instagram TEXT DEFAULT '@kapturise', linkedin TEXT DEFAULT 'Kapturise', tiktok TEXT DEFAULT '@kapturise', youtube TEXT DEFAULT 'Kapturise', facebook TEXT DEFAULT 'Kapturise', about TEXT, usp TEXT, founded TEXT, team_size TEXT, updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE activity_logs (id SERIAL PRIMARY KEY, agent_id TEXT REFERENCES agents(id), message TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE api_keys (id INTEGER PRIMARY KEY DEFAULT 1, gemini_key TEXT, bland_key TEXT, bland_phone TEXT, updated_at TIMESTAMPTZ DEFAULT NOW());
ALTER TABLE agents ENABLE ROW LEVEL SECURITY; ALTER TABLE leads ENABLE ROW LEVEL SECURITY; ALTER TABLE investors ENABLE ROW LEVEL SECURITY; ALTER TABLE pricing ENABLE ROW LEVEL SECURITY; ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY; ALTER TABLE scripts ENABLE ROW LEVEL SECURITY; ALTER TABLE social_accounts ENABLE ROW LEVEL SECURITY; ALTER TABLE company_info ENABLE ROW LEVEL SECURITY; ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY; ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON agents FOR ALL USING (true) WITH CHECK (true); CREATE POLICY "Allow all" ON leads FOR ALL USING (true) WITH CHECK (true); CREATE POLICY "Allow all" ON investors FOR ALL USING (true) WITH CHECK (true); CREATE POLICY "Allow all" ON pricing FOR ALL USING (true) WITH CHECK (true); CREATE POLICY "Allow all" ON campaigns FOR ALL USING (true) WITH CHECK (true); CREATE POLICY "Allow all" ON scripts FOR ALL USING (true) WITH CHECK (true); CREATE POLICY "Allow all" ON social_accounts FOR ALL USING (true) WITH CHECK (true); CREATE POLICY "Allow all" ON company_info FOR ALL USING (true) WITH CHECK (true); CREATE POLICY "Allow all" ON activity_logs FOR ALL USING (true) WITH CHECK (true); CREATE POLICY "Allow all" ON api_keys FOR ALL USING (true) WITH CHECK (true);
INSERT INTO company_info (id, name, tagline, about, usp, founded) VALUES (1, 'Kapturise', 'Make it your moment.', 'Dubai-based creative production agency.', 'Full-service creative partner. 24-48hr delivery.', '2024');
INSERT INTO api_keys (id) VALUES (1);